name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: bot_net_worth-${{ inputs.release_version }}
        path: target/release/bot_net_worth

  publish:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: bot_net_worth-${{ inputs.release_version }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{inputs.release_version }}
          draft: true
          artifacts: ${{ steps.download-artifact.download-path }}

